### ISSUE TITLE
False positive for YARD/CollectionStyle

### ISSUE THREAD

**Issue by frsantos** [ksss/rubocop-yard#24]
The following code reports an offense, but the YARD is right according to https://rubydoc.info/gems/yard/file/docs/Tags.md#order-dependent-lists

```ruby
class Test
  # @param [Array<(Date, Integer)>] params
  def test(params)
  end
end
```

```
test.rb:2:3: C: [Correctable] YARD/CollectionStyle: Array<(Date, Integer)> is using short style syntax
  # @param [Array<(Date, Integer)>] params
```

**Comment by ksss** [comment]
Yes, it is valid syntax in YARD.
This cop deals with uniformity of notation.
If you want to use long style it should be `Array<Array(Date, Integer)>`,
If you want to use short style it should be `<(Date, Integer)>`.
If you want to mix them, it might be better to be able to configure them separately for Array, Taple, and Hash.

**Comment by frsantos** [comment]
No, the notation that is allowed by the documentation is not an array of arrays, but an array of 2 elements with fixed types. That is:

```ruby
# Array<Array<Date, Integer>>
a = [[0, Date.new, 1, Date.new, 4, 5, 6, Date.new, Date.new]]

# Array<(Date, Integer)>
b = [Date.new, 4]

# Array<(Date, Integer)>
c = [4, Date.new] => WRONG!!!!, as it not a single Date followed by a single Integer

**Comment by ksss** [comment]
In that example, the `b` case is incorrect.

I interpret this as follows.

- `(type)` is fixed collection (aka tuple).
- `(type)` is the short hand of `Array(type)`.
- There can be a type `List(Date, Integer)`.

```rb
::YARD::DocstringParser.new.parse("@param [(Date, Integer)]").tags.first.explain_types
# => "an Array containing (a Date followed by an Integer)"

::YARD::DocstringParser.new.parse("@param [List(Date, Integer)]").tags.first.explain_types
# => "a List containing (a Date followed by an Integer)"

::YARD::DocstringParser.new.parse("@param [Array<(Date, Integer)>]").tags.first.explain_types
# => "an Array of (an Array containing (a Date followed by an Integer))"
```

**Comment by frsantos** [comment]
This is what docs say:

>  For instance, an Array containing a String, Fixnum and Hash in that order (and having exactly those 3 elements) would be listed as: Array<(String, Fixnum, Hash)>

So I interpret it as the long syntax of the array containing a tuple, not the short syntax. Is the docs wrong then?

```ruby
::YARD::DocstringParser.new.parse("@param [Array(Date, Integer)]").tags.first.explain_types
=> "an Array containing (a Date followed by an Integer)"

::YARD::DocstringParser.new.parse("@param [Array<Date, Integer>]").tags.first.explain_types
=> "an Array of (Dates or Integers)"

::YARD::DocstringParser.new.parse("@param [Array<(Date, Integer)>]").tags.first.explain_types
=> "an Array of (an Array containing (a Date followed by an Integer))"
```

None of them match what documentation says.

**Comment by ksss** [comment]
The syntax `Array(type)` is often used within the YARD gem code.
https://github.com/search?q=repo%3Alsegal%2Fyard%20Array(&type=code

If you feel there is a problem with the documentation, I suggest you create an issue on the YARD repo.

**Comment by frsantos** [comment]
OK, So the documentation is wrong in this point.

**Comment by frsantos** [comment]
I'll create an issue on their repo.

**Comment by frsantos** [comment]
Created the issue and a PR https://github.com/lsegal/yard/issues/1523
