### ISSUE TITLE
YARD warning log is output when executing rubocop

### ISSUE THREAD

**Issue by euglena1215** [ksss/rubocop-yard#25]
In my application, when I run `rubocop` after requiring rubocop-yard, I get the following WARN log when parsing YARD.

```
root@eacd66a1e36e:/usr/src/app# bundle exec rubocop
[warn]: Invalid tag format for @return
[warn]: Invalid tag format for @return
Inspecting 1234 files
....
````

The problem is that the YARD notation is wrong, but I think that problem is better solved separately from rubocop.

YARD allows us to change the log level of a logger only for a specific block as follows.

```rb
YARD::Logger.instance.enter_level(YARD::Logger::ERROR) do
  # Write the logic to parse YARD here
end
```

What do you think about suppressing warning logs?
Let me know what you think!

**Comment by ksss** [comment]
Thank you for reporting.
I agree with you.
When rubocop is executed, the warning of YARD itself should not be output, but should be reported as an offenct of rubocop.

**Comment by ksss** [comment]
To reproduce the problem, could you add a test case that does not produce warnings, or provide a sample YARD case that does produce warnings?
