### ISSUE TITLE
YARD/TagTypeSyntax does not allow literals

### ISSUE THREAD

**Issue by aaronmallen** [ksss/rubocop-yard#33]
## Expected Behavior

Literal values are a valid type in Yard and the `YARD/TagTypeSyntax` cop should respect them as such.

## Actual Behavior

Using literal values as types raises a `YARD/TagTypeSyntax` error

## Steps to reproduce:

1. Document a method and have a param have a literal type: `@param my_symbol [:foo, :bar, :baz]`
2. Run rubocop
3. Notice `YARD/TagTypeSyntax` errors

## Current Workaround:

```ruby
#  rubocop:disable Yard/TagTypeSyntax

# Describe some method
#
# @param my_symbol [:foo, :bar, :baz] a foo bar or baz
# @return [:foo, :bar, :baz] the passed symbol
def some_method(my_symbol)
  raise ArgumentError, "Invalid symbol: #{my_symbol}" unless %i[foo bar baz].include?(my_symbol)
  my_symbol
end
# rubocop:enable Yard/TagTypeSyntax
```

**Comment by ksss** [comment]
@aaronmallen Thank you for the feedback.

`YARD/TagTypeSyntax` call YARD's API.
https://github.com/ksss/rubocop-yard/blob/b574f3c4e375754e8989a66b8d234cb7745ea07d/lib/rubocop/cop/yard/helper.rb#L19

Perhaps symbol literals are not allowed in YARD.

```rb
$ irb -r yard
irb(main):001> ::YARD::Tags::TypesExplainer::Parser.parse("Integer")
=> [#<YARD::Tags::TypesExplainer::Type:0x00000001200a1e20 @name="Integer">]
irb(main):002> ::YARD::Tags::TypesExplainer::Parser.parse(":foo")
=> invalid character at : (SyntaxError)
```

https://rubydoc.info/gems/yard/file/docs/Tags.md#literals

However, I agree that it is inconvenient.

**Comment by aaronmallen** [comment]
Wild, I had assumed since the parser seems to handle them just fine on `yard doc` or `yard server` that they were legal yard syntax. I apologized for not verifying my assumption.
